INSERT INTO pantheon (name, description) VALUES
('Greek Pantheon', 'THE IMMORTALS of the Ancient Greek pantheon can be divided into roughly eight classes. THE FIRST of these were the PROTOGENOI or First Born gods. These were the primeval beings who emerged at creation to form the very fabric of universe: Earth, Sea, Sky, Night, Day, etc. Although they were divinites they were purely elemental in form: Gaia was the literal Earth, Pontos the Sea, and Ouranos the Dome of Heaven. However they were sometimes represented assuming anthroporphic shape, albeit ones that were indivisible from their native element. Gaia the earth, for example, might manifest herself as a matronly woman half-risen from the ground ; and Thalassa the sea might lift her head above the waves in the shape of a sea-formed woman. THE SECOND were the nature DAIMONES (Spirits) and NYMPHAI who nurtured life in the four elements. E.g. fresh-water Naiades, forest Dryades, beast-loving Satyroi, marine Tritones, etc. THE THIRD were the body- and mind-affecting DAIMONES (Spirits). E.g. Sleep (Hypnos), Love (Eros), Joy (Euphrosyne), Hate (Eris), Fear (Phobos), Death (Thanatos), Old Age (Geras), etc. THE FOURTH class consisted of the THEOI (Gods) who controlled the forces of nature and bestowed civilised arts upon mankind.'),
('Egyptian Pantheon', 'Egyptian religion had ancient origins and lasted for at least 3,500 years. The Egyptians saw divinity in everything — in river, desert, and vegetation; in the sun, moon, and stars; in animals and kings; in birth and death. They created a vast and confusing multitude of gods. There are literally hundreds of deities, some having animal form, some depicted with human bodies and animal heads, and some of human form. A god like Ra had dozens of names, and often gods had two or more shapes apiece. Political and priestly pressures sometimes brought in new gods and swept the old ones aside. Furthermore, Egyptian religion was local, with different religious centers having different gods and cosmogonies. After listing a few of the major gods, we will give the account of the creation according to the priests at Heliopolis.'),
('Norse Pantheon', 'Norse mythology is the body of mythology practised in Scandinavia (Norway, Sweden and Denmark) stemming from paganism and continuing after the introduction of Christianity. Norse mythology encompasses figures and stories from numerous sources, medieval manuscripts, archaeological evidence and folk tradition, from before and after the pagan era. Some of these deities include Thor, Odin, Freyja, Skaoi, Njoror and Loki.'),
('Aztec Pantheon', 'Aztec religion, the religion followed by the Aztecs, a Nahuatl-speaking people who ruled a large empire in central and southern Mexico in the 15th and early 16th centuries. Aztec religion was syncretistic, absorbing elements from many other Mesoamerican cultures. At base, it shared many of the cosmological beliefs of earlier peoples, notably the Maya, such as that the present earth was the last in a series of creations and that it occupied a position between systems of 13 heavens and 9 underworlds.'),
('Hawaiian Pantheon', 'Hawaiian religion refers to the indigenous religious beliefs and practices of native Hawaiians, also known as the kapu system. Hawaiian religion is based largely on the tapu religion common in Polynesia and likely originated among the Tahitians and other Pacific islanders who landed in Hawaiʻi between 500 and 1300 AD.[1] It is polytheistic and animistic, with a belief in many deities and spirits, including the belief that spirits are found in non-human beings and objects such as other animals, the waves, and the sky.'),
('Hindu Pantheon', 'The Pantheon of Hindu Gods is vast. Yet, in fact, Hindus are a monotheistic religion worshiping one God. Hindus believe that there is only one ultimate reality; Brahman. Brahman is a supreme spirit that permeates everything. Brahman is entirely impersonal, and entirely impossible to describe. Everything in the universe is part of Brahman, but Brahman is more than the sum of everything in the universe. The Hindu gods; Shiva, Parvati, Krishna, Vishnu, Lakshmi, Ganesh, Nataraja, Devi, Saraswati, Shakti, Buddha, Kali, Murugan, Patanjali, and Hanuman serve as a way in which devotees can see, touch and feel this unknowable God, Brahman. They give the layperson a tangible, knowable aspect of the Supreme Being.');

INSERT INTO gods (name, god_goddess_of, info, fun_facts, pantheon_name) VALUES
('Zeus', 'God of the Sky', 'The chief Greek deity, Zeus is considered the ruler, protector, and father of all gods and humans. Zeus is often depicted as an older man with a beard and is represented by symbols such as the lightning bolt and the eagle.', 'The Olympics were held each year by the Greeks in honor of Zeus.', 'Greek Pantheon'),
('Posedion', 'God of the Sea', 'He made horses.', 'His weapon and main symbol was the trident. ', 'Greek Pantheon'),
('Hades', 'God of the Underworld', 'Hades helm or Cap of Hades allowed the wearer to turn invisible.', 'He was the most fair of gods', 'Greek Pantheon'),
('Apollo', 'God of Sun and Light', 'Apollo personified the qualities of the sun with his glowing golden hair, and  he was responsible for bringing the sun to the earth each day while riding on a golden chariot.', 'Apollo had many powers, but the power to heal, power to prophesize, and the power to make music were among his most important.', 'Greek Pantheon'),
('Hephaestus', 'God of fire, the forge, blacksmithing, metalworking, and masonry.', 'Hephaestus constructed the armor and weapons for Olympus, as well as constructed many accessories that helped other Greek heroes in mythology.', 'He was rasied by mortals.', 'Greek Pantheon'),
('Ares', 'God of War', 'He was the first child of Zeus and Hera.', 'He was characterized to be a coward.', 'Greek Pantheon'),
('Athena', 'Goddess of Wisdom', 'Athena embodied cold rationality, tactics, and strategy.', 'Zeus considered Athena to be his favorite child.', 'Greek Pantheon'),
('Atum', 'Sun God', 'A primeval cosmic god, Atum is the sun god as creator, the substance from which all creation unfurled. He is the Lord of the Universe.', ' In his human form, he represents the king of Egypt, who wears the Double Crown of Egypt.', 'Egyptian Pantheon'),
('Odin', 'God of all Gods', 'Odin has many names and is the god of both war and death. Half of the warriors who die in battle are taken to his hall of Valhalla.', 'He is the one-eyed All-Father, who sacrificed his eye in order to see everything that happens in the world.', 'Norse Pantheon'),
('Tlaloc', 'God of Rain', 'Tlaloc is also the god of agriculture and fertility. He is associated with weather events like storms, snow, floods, lightning and ice.', 'He is often depicted with large eyes and fangs.', 'Aztec Pantheon'),
('Pele', 'Goddess of volcanoes and fire.', 'Creator of the Hawaiian Islands.', 'She is said to live in the crater of Kilauea, one of the most active volcanoes on the island of Hawaii.', 'Hawaiian Pantheon'),
('Ganesha', 'Remover of obstacles', 'The large elephant head of Lord Ganesha symbolizes wisdom, understanding, and a discriminating intellect that one must possess to attain perfection in life.', 'Lord Ganesha is usually portrayed wearing red and yellow clothes.', 'Hindu Pantheon');